year 2-3 transition

diff --git a/web/conf/re_ibe b/web/conf/re_ibe
--- a/web/conf/re_ibe
+++ b/web/conf/re_ibe
@@ -1,6 +1,8 @@
 #!/bin/bash 
 
-# $Id: re_ibe,v 20150903.99115129 2015/09/03 18:51:29 modell ipac $
+# $Id: re_ibe,v 20160120.99121400 2016/01/20 20:14:00 irsawise unknown $
+
+# {{{  # hdr
 
 # [re-]start IBE
 
@@ -10,6 +12,8 @@
 # $0 bacchus_5000
 # $0 sudo bacchus_8000
 # $0 sudo hades_8000
+
+# }}}
 
 # {{{  # notes
 
@@ -33,151 +37,167 @@
 
 # }}}
 
-function LC () {
-    tr '[:upper:]' '[:lower:]'
-}
+# {{{  funcs
 
-export cn=$0;
-export cf=` pwd `;
-export ca=` basename "${cn}" `;
-export ci=`  dirname "${cn}" `;
+    function usage () {
+        echo "";
+        echo " * [re-] start IBE";
+        echo "";
+        echo "  usage:";
+        echo "";
+        echo "    ${ca} help | [no[sudo]] [instances/]sysname_portnum[.json]";
+        echo "";
+        echo "      (e.g.)";
+        echo "";
+        echo "        cd    .../ibe/web/conf";
+        echo "";
+        echo "        ${ca} ${typ}";
+        echo "        ${ca} sudo ${typ}";
+        echo "";
+        echo "          defaults to nosudo";
+        echo "";
+        echo "            (sudo only used to control apache)";
+        echo "";
+        echo "  currently available instances:";
+        echo "";
+        ls -1 instances | sed 's/^/       /' | sed 's/\.json//';
+        echo "";
+    }
 
-sudo="sudo";
-sudo="";
+    function LC () {
+        tr '[:upper:]' '[:lower:]'
+    }
 
-inst=instances;
-suff=json;
+    function UC () {
+        tr '[:lower:]' '[:upper:]' 
+    }
 
-syst=bacchus
-port=5001;
+# }}}
+# {{{  cfg
 
-syst=$( uname -n | LC );
+    export cn=$0;
+    export cf=` pwd `;
+    export ca=` basename "${cn}" `;
+    export ci=`  dirname "${cn}" `;
 
-sprt=${syst}_${port};
-
-export typ=${sprt};
-
-dflt=${inst}/${typ}.${suff};
-
-cp_dev=./apachectl.sh;
-cp_ops=/etc/init.d/irsa_web;
-
-cp_use=${cp_dev};
-
-if ! echo "${syst}" | grep -i bacchus >/dev/null 2>&1; then
-    cp_use=${cp_ops};
-fi
-
-if ! [[ -r ${cp_use} ]]; then
-    echo "${cp_use} is not readable";
-    cp_use=${cp_dev};
-    echo "reverting to ${cp_use}";
-fi
-
-if ! [[ -x ${cp_use} ]]; then
-    echo "error -- ${cp_use} is not executable";
-    exit 9;
-fi
-
-function usage () {
-  echo "";
-  echo " * [re-] start IBE";
-  echo "";
-  echo "  usage:";
-  echo "";
-  echo "    ${ca} help | [no[sudo]] [instances/]sysname_portnum[.json]";
-  echo "";
-  echo "      (e.g.)";
-  echo "";
-  echo "        cd    .../ibe/web/conf";
-  echo "        ${ca} ${typ}";
-  echo "";
-  echo "          defaults to nosudo";
-  echo "";
-  echo "            (sudo only used to control apache)";
-  echo "";
-  echo "  currently available instances:";
-  echo "";
-  ls -1 instances | sed 's/^/       /' | sed 's/\.json//';
-  echo "";
-}
-
-if echo $* | grep -i    help >/dev/null 2>&1 || \
-   echo $* | grep -i -- '-h' >/dev/null 2>&1    ; then
-   usage;
-   exit 10;
-fi
-
-if [[ "_nosudo_" == "_$1_" ]]; then
-    shift;
+    sudo="sudo";
     sudo="";
 
-elif [[ "_sudo_" == "_$1_" ]]; then
-    shift;
-    sudo="sudo";
-fi
+    inst=instances;
+    suff=json;
 
-# sys_nm=` uname -n `;
-sys_nm=${syst};
+    syst=bacchus
+    port=5001;
 
-xdp=` pwd -P `;
+    syst=$( uname -n | LC );
 
-xdt=` basename "${xdp}"  `;
-xdh=`  dirname "${xdp}"  `;
+    sprt=${syst}_${port};
 
-xdT=` basename "${xdh}" `;
-xdH=`  dirname "${xdh}" `;
+    export typ=${sprt};
 
-xDT=` basename "${xdH}" `;
-xDH=`  dirname "${xdH}" `;
+    dflt=${inst}/${typ}.${suff};
 
-if [[ "conf" != "${xdt}" ]] ||  
-   [[ "web"  != "${xdT}" ]] ||  
-   ! echo "${xDT}" | grep -i ibe >/dev/null 2>&1; then
-  echo "error -- expected current directory '${xdp}' path ending to look like .../*ibe*/web/conf";
-  exit 11;
-fi
+    cp_dev=./apachectl.sh;
+    cp_ops=/etc/init.d/irsa_web;
 
-# if [[ ""        == "$1"      ]] && 
-#    [[ "bacchus" != "${syst}" ]]    ; then
-#    usage;
-#    exit 12;
-# fi
+    cp_use=${cp_dev};
 
-if [[ "" == "$1" ]]; then
-   usage;
-   exit 12;
-fi
+    if ! echo "${syst}" | grep -i bacchus >/dev/null 2>&1; then
+        cp_use=${cp_ops};
+    fi
 
-given=${dflt};
-# 
-if [[ "" != "$1" ]]; then
-  given="$1";
-fi
+    if ! [[ -r ${cp_use} ]]; then
+        echo "${cp_use} is not readable";
+        cp_use=${cp_dev};
+        echo "reverting to ${cp_use}";
+    fi
 
-cfg=${given};
-# 
-if ! echo "${given}" | grep -i json >/dev/null 2>&1; then
-  cfg=${given}.json;
-fi
+    if ! [[ -x ${cp_use} ]]; then
+        echo "error -- ${cp_use} is not executable";
+        exit 9;
+    fi
 
-fcfg=${cfg};
-# 
-if ! [[ -r "${cfg}" ]]; then
-  # echo "cannot read config @ '${cfg}' ";
-  # echo "trying  ...  '${inst}/${cfg}' ";
-  fcfg=${inst}/${cfg};
-fi
+# }}}
+# {{{  args
 
-if ! [[ -r "${fcfg}" ]]; then
-  echo "cannot read config @ '${fcfg}' ";
-  exit 13;
-fi
+    if echo $* | grep -i    help >/dev/null 2>&1 || \
+    echo $* | grep -i -- '-h' >/dev/null 2>&1    ; then
+    usage;
+    exit 10;
+    fi
 
-if ! echo "${fcfg}" | grep -i ${sys_nm} >/dev/null 2>&1; then
-  echo "error -- expected config name '${fcfg}' would include system name '${sys_nm}'";
-  exit 14;
-fi
+    if [[ "_nosudo_" == "_$1_" ]]; then
+        shift;
+        sudo="";
+
+    elif [[ "_sudo_" == "_$1_" ]]; then
+        shift;
+        sudo="sudo";
+    fi
+
+    # sys_nm=` uname -n `;
+    sys_nm=${syst};
+
+    xdp=` pwd -P `;
+
+    xdt=` basename "${xdp}"  `;
+    xdh=`  dirname "${xdp}"  `;
+
+    xdT=` basename "${xdh}" `;
+    xdH=`  dirname "${xdh}" `;
+
+    xDT=` basename "${xdH}" `;
+    xDH=`  dirname "${xdH}" `;
+
+    if [[ "conf" != "${xdt}" ]] ||  
+    [[ "web"  != "${xdT}" ]] ||  
+    ! echo "${xDT}" | grep -i ibe >/dev/null 2>&1; then
+    echo "error -- expected current directory '${xdp}' path ending to look like .../*ibe*/web/conf";
+    exit 11;
+    fi
+
+    # if [[ ""        == "$1"      ]] && 
+    #    [[ "bacchus" != "${syst}" ]]    ; then
+    #    usage;
+    #    exit 12;
+    # fi
+
+    if [[ "" == "$1" ]]; then
+    usage;
+    exit 12;
+    fi
+
+    given=${dflt};
+    # 
+    if [[ "" != "$1" ]]; then
+    given="$1";
+    fi
+
+    cfg=${given};
+    # 
+    if ! echo "${given}" | grep -i json >/dev/null 2>&1; then
+    cfg=${given}.json;
+    fi
+
+    fcfg=${cfg};
+    # 
+    if ! [[ -r "${cfg}" ]]; then
+    # echo "cannot read config @ '${cfg}' ";
+    # echo "trying  ...  '${inst}/${cfg}' ";
+    fcfg=${inst}/${cfg};
+    fi
+
+    if ! [[ -r "${fcfg}" ]]; then
+    echo "cannot read config @ '${fcfg}' ";
+    exit 13;
+    fi
+
+    if ! echo "${fcfg}" | grep -i ${sys_nm} >/dev/null 2>&1; then
+    echo "error -- expected config name '${fcfg}' would include system name '${sys_nm}'";
+    exit 14;
+    fi
+
+# }}}
 
 echo "BEGIN"                            && \
   ${sudo} ${cp_use} stop                && \
